print('Primeira Maneira')
print('-'*20)
co = float(input('Comprimento do Cateto Oposto: '))
ca = float(input('Comprimento do Cateto Adjacente: '))
hi = (co ** 2 + ca ** 2) ** (1/2)
print('A hipotenusa vai medir: {:.2f}'.format(hi))
print('-'*20)
print('Segunda Maneira')
print('-'*20)
import math
co = float(input('Comprimento do Cateto Oposto: '))
ca = float(input('Comprimento do Cateto Adjacente: '))
hi = math.hypot(co, ca)
print('A hipotenusa vai medir: {:.2f}'.format(hi))
print('-'*20)
